import dotenv from "dotenv";
import { EnvConfig } from "./types";
dotenv.config();

const {
  PORT,
  DB_URL,
  JWT_SECRET_AUTH,
  JWT_AUTH_EXPIRY,
  JWT_EXPIRY,
  MAIL_HOST,
  MAIL_PORT,
  MAIL_USERNAME,
  MAIL_PASSWORD,
  MAIL_EMAIL,
  EMAIL_VERIFY_TOKEN_SECRET_KEY,
  DOMAIN_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
} = process.env;

const envConfig = {
  PORT: PORT || 8000,
  DB_URL: DB_URL || "mongodb://127.0.0.1:27017",
  JWT_SECRET_AUTH,
  JWT_AUTH_EXPIRY,
  JWT_EXPIRY,
  MAIL_HOST,
  MAIL_PORT,
  MAIL_USERNAME,
  MAIL_PASSWORD,
  MAIL_EMAIL,
  EMAIL_VERIFY_TOKEN_SECRET_KEY,
  DOMAIN_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
} as EnvConfig;

export default envConfig;
